name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  pre-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: install gox
      run: go get github.com/mitchellh/gox

    - name: Build
      run: |
        go build -v 
        gox -osarch="linux/amd64"
        gox -os="linux"
    
    - name: releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GH_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Releases Build"
        files: zredirector_*
